title: Jesse Schauer
email: JesseSchauer@outlook.com
description: >-
  One-man dev shop. The merc they call in to get stuff done. I build trust, not just code.
baseurl: ""
url: "https://jesseschauer.com"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme


sidebar:
  nav: "main"
